name: Deploy to Production

on:
  push:
    tags:
      - 'v*' # Деплой только по тегу

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install sshpass
        run: sudo apt-get update && sudo apt-get install -y sshpass

      - name: Deploy via sshpass
        env:
          SSHPASS: ${{ secrets.SSH_PASS }}
        run: |
          sshpass -p "$SSHPASS" ssh -o StrictHostKeyChecking=no root@${{ secrets.SSH_HOST }} '
            cd /root/project/Landing/AI-bots && \
            git fetch --all --tags && \
            git checkout ${{ github.ref_name }} && \
            echo "📋 Останавливаем только aibotsnews.service..." && \
            systemctl stop aibotsnews.service || true && \
            echo "⏳ Ждем остановки..." && \
            sleep 5 && \
            echo "🧹 Очищаем кэш только для этого проекта..." && \
            rm -rf .next/ node_modules/ || true && \
            echo "📦 Устанавливаем зависимости..." && \
            npm ci --production && \
            echo "🔨 Собираем проект..." && \
            npm run build && \
            echo "🚀 Запускаем только aibotsnews.service..." && \
            systemctl start aibotsnews.service && \
            echo "⏳ Ждем запуска..." && \
            sleep 10 && \
            systemctl status aibotsnews.service
          '

      - name: Notify Telegram (success)
        if: success()
        run: |
          echo "📱 Отправляем уведомление об успешном деплое..."
          RESPONSE=$(curl -s -w "\n%{http_code}" -X POST https://api.telegram.org/bot${{ secrets.TELEGRAM_TOKEN }}/sendMessage \
            -d chat_id=${{ secrets.ADMIN_IDS }} \
            -d text="✅ Деплой по тегу ${{ github.ref_name }} завершён успешно!")
          
          HTTP_CODE=$(echo "$RESPONSE" | tail -n1)
          RESPONSE_BODY=$(echo "$RESPONSE" | head -n -1)
          
          echo "HTTP Code: $HTTP_CODE"
          echo "Response: $RESPONSE_BODY"
          
          if [ "$HTTP_CODE" != "200" ]; then
            echo "❌ Ошибка отправки Telegram уведомления: $HTTP_CODE"
            exit 1
          else
            echo "✅ Telegram уведомление отправлено успешно"
          fi

      - name: Notify Telegram (failure)
        if: failure()
        run: |
          echo "📱 Отправляем уведомление об ошибке деплоя..."
          RESPONSE=$(curl -s -w "\n%{http_code}" -X POST https://api.telegram.org/bot${{ secrets.TELEGRAM_TOKEN }}/sendMessage \
            -d chat_id=${{ secrets.ADMIN_IDS }} \
            -d text="❌ Ошибка деплоя по тегу ${{ github.ref_name }}. Проверь логи GitHub Actions!")
          
          HTTP_CODE=$(echo "$RESPONSE" | tail -n1)
          RESPONSE_BODY=$(echo "$RESPONSE" | head -n -1)
          
          echo "HTTP Code: $HTTP_CODE"
          echo "Response: $RESPONSE_BODY"
          
          if [ "$HTTP_CODE" != "200" ]; then
            echo "❌ Ошибка отправки Telegram уведомления об ошибке: $HTTP_CODE"
            echo "Это может означать проблемы с TELEGRAM_TOKEN или ADMIN_IDS"
          else
            echo "✅ Telegram уведомление об ошибке отправлено успешно"
          fi

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 