name: Test Telegram Notifications

on:
  workflow_dispatch: # Ручной запуск

jobs:
  test-telegram:
    runs-on: ubuntu-latest
    
    steps:
      - name: Test Telegram Success Notification
        run: |
          echo "🧪 Тестируем отправку уведомления об успехе..."
          
          # Проверяем наличие секретов
          if [ -z "${{ secrets.TELEGRAM_TOKEN }}" ]; then
            echo "❌ TELEGRAM_TOKEN не настроен"
            exit 1
          fi
          
          if [ -z "${{ secrets.ADMIN_IDS }}" ]; then
            echo "❌ ADMIN_IDS не настроен"
            exit 1
          fi
          
          echo "✅ Секреты настроены"
          echo "TELEGRAM_TOKEN: ${#{{ secrets.TELEGRAM_TOKEN }}} символов"
          echo "ADMIN_IDS: ${{ secrets.ADMIN_IDS }}"
          
          # Тестируем отправку
          RESPONSE=$(curl -s -w "\n%{http_code}" -X POST https://api.telegram.org/bot${{ secrets.TELEGRAM_TOKEN }}/sendMessage \
            -d chat_id=${{ secrets.ADMIN_IDS }} \
            -d text="🧪 Тестовое уведомление от GitHub Actions - $(date)")
          
          HTTP_CODE=$(echo "$RESPONSE" | tail -n1)
          RESPONSE_BODY=$(echo "$RESPONSE" | head -n -1)
          
          echo "HTTP Code: $HTTP_CODE"
          echo "Response: $RESPONSE_BODY"
          
          if [ "$HTTP_CODE" = "200" ]; then
            echo "✅ Telegram уведомление работает корректно"
          else
            echo "❌ Ошибка отправки Telegram уведомления"
            echo "Возможные причины:"
            echo "1. Неверный TELEGRAM_TOKEN"
            echo "2. Неверный ADMIN_IDS"
            echo "3. Бот заблокирован"
            exit 1
          fi